<?php

use Slayer\Test\Model\OrderModel;
use Slayer\Test\ViewModel\ExtraInfo;

/** @var Slayer\Test\Block\Order $block */
$blockName = $block->getNameInLayout();

///** @var Slayer\Test\Model\ResourceModel\Order\Collection $orderCollection */
//$orderCollection = $block->getOrderCollection();
//$sqlString = $orderCollection->getSelect()->__toString();

$orders = $block->getOrders();

/** @var ExtraInfo $viewModel */
$viewModel = $block->getData('view_model');
?>

<h1 class="custom-block block-name" style="color: #fc6c24; font-weight: bold; text-shadow: 1px 1px 1px #000000;"><?= __('My Orders Collection: '); ?><?= $blockName ?>!</h1>
<!--<h2 class="sql-query">Query was:
    <span style="color: red"><?/*= $sqlString */?></span>
</h2>-->
<?php if ($viewModel && $viewModel->getCurrentDate()): ?>
    <h3 style="color: darkblue"><?= __('Current date is: %1', $viewModel->getCurrentDate()); ?></h3>
<?php endif; ?>
<div class="container">
    <?php if ($orders): ?>
        <?php foreach ($orders as $order): ?>
            <?php /** @var OrderModel $order */ ?>
            <div class="customer">
                <h3 class="user-id" style="color: darkred;"><?= __('User ID: '); ?><span style="color: #0e301a"><?= $order->getUserId() ?></span></h3>
                <h3 class="order-id" style="color: darkred;"><?= __('Order ID: '); ?><span style="color: #0e301a"><?= $order->getOrderId() ?></span></h3>
                <h3 class="order-name" style="color: darkred;"><?= __('Order name: '); ?><span style="color: #0e301a"><?= $order->getOrderName() ?></span></h3>
                <h3 class="created-at" style="color: darkred;"><?= __('Created At: '); ?><span style="color: #0e301a"><?= $order->getCreatedAt() ?></span></h3>
                <h3 class="price" style="color: darkred;"><?= __('Price: '); ?><span style="color: #0e301a"><?= $order->getPrice() ?> грн.</span></h3>
                <p>
                    <a class="go-back" href="<?= $block->getUrl('test') ?>" style="font-weight: bolder; color: #006bb4; font-size: 1.5em; text-decoration: none;"
                       onmouseover="this.style.color='#4ca939';" onmouseout="this.style.color='darkblue';"><?= __('Go Back'); ?></a>
                </p>
                <hr>
            </div><br>
        <?php endforeach; ?>
    <?php endif; ?>
</div>