<?php
$blockName = $block->getNameInLayout();
?>

<h1 class="my-block">My custom information in my <span style="font-weight: bold; color: darkred"><?= $blockName ?>!</span></h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum eligendi molestias odit quia, quibusdam recusandae
    repellendus repudiandae! Blanditiis cumque doloremque laborum nesciunt reprehenderit voluptate. Atque consequuntur
    corporis cupiditate dignissimos expedita, facilis inventore labore magnam mollitia nisi non quae quam quos repellat
    sit tempore vel vero? Consequuntur dignissimos doloremque illum impedit, quod quos! Adipisci asperiores deleniti
    doloribus error exercitationem harum iste itaque labore, libero veniam. Esse facere ipsam minus nam, odit possimus
    similique. Accusantium ad amet aspernatur atque, beatae dicta dolore enim, eos facere fugiat fugit hic iste iusto
    maiores molestiae molestias nesciunt officia pariatur perspiciatis quae quam quibusdam quidem quisquam quod quos
    repellendus suscipit. Cupiditate doloremque enim explicabo facere nesciunt nihil, provident reprehenderit ullam!
    Accusamus adipisci animi asperiores at atque cumque dolore doloremque dolores doloribus ducimus, eius esse est eum
    harum id ipsa ipsam itaque laboriosam magnam maxime minus numquam perferendis quae quos repellat repellendus saepe
    sapiente sed sit soluta suscipit tempora ut vel! Asperiores consequatur culpa deserunt et nulla obcaecati
    praesentium quidem rem repellendus sapiente. Dolor eligendi illum iste nostrum vitae? Aliquam amet beatae dicta
    dolorem eius, eos est et, explicabo facilis illo maiores neque nobis odio odit, officiis placeat quasi quis
    reiciendis sequi vitae. Laborum saepe tenetur vitae?</p>