<?php

use Slayer\Test\Model\ManufacturerModel;

/** @var Slayer\Test\Block\Customer $block */
$blockName = $block->getNameInLayout();
$str = $block->getCacheKey();
$pattern = '/[^A-Z_].*/';
preg_match($pattern, $str, $matches);
$cacheKey = implode($matches);

/** @var \Slayer\Test\Model\ResourceModel\Customer\Collection $customerCollection */
$customerCollection = $block->getCustomerCollection();
?>

<h1 class="custom-block block-name">My custom information in my <?= $blockName ?>!</h1>
<p><b><span class="cache">We get block with cache key = </span><span class="cache-number"><?= $cacheKey; ?></span></b></p>
<div class="container">
    <?php foreach ($customerCollection as $customer): ?>
        <?php /** @var ManufacturerModel $customer */ ?>
        <div class="customer">
            <h3 class="entity-id">Entity ID: <?= $customer->getId() ?></h3>
            <h3 class="name">Name: <?= $customer->getName() ?></h3>
            <h3 class="surname">Surname: <?= $customer->getSurname() ?></h3>
            <h3 class="email">Email: <?= $customer->getEmail() ?></h3>
            <h3 class="phone-number">Phone number: +<?= $customer->getPhoneNumber() ?></h3>
            <p>
            <a class="read-more" href="<?= $block->getUrl('test/index/customers', ['user_id' => $customer->getId()])?>">See Customer Orders</a>
            </p><hr>
        </div><br>
    <?php endforeach; ?>
</div>