<?php
use Slayer\Mobile\Block\Phone;
use Slayer\Mobile\Api\Data\PhoneInterface;
use Slayer\Mobile\Model\PhoneModel;
use Slayer\Mobile\ViewModel\ExtraInfo;

/**@var Phone $block */
$blockName = $block->getNameInLayout();
/** @var PhoneInterface[] $phones */
$phones = $block->getPhones();
/** @var ExtraInfo $viewModel */
$viewModel = $block->getData('view_model');
?>

<h1 class="manufacturer-block-name"><?= $blockName ?>!</h1>
<div class="manufacturer-container">
    <?php if ($viewModel && $viewModel->getCurrentDate()): ?>
        <h3 class="view-model"><?= __('Now is ')?><span><?= __($viewModel->getCurrentDate()) ?></span></h3>
    <?php endif; ?>
    <?php if ($phones): ?>
        <?php foreach ($phones as $phone): ?>
            <?php /** @var PhoneModel $phone */ ?>
            <div class="manufacturer">
                <h3 class="model"><?= $phone->getModel() ?></h3>
                <h3 class="os">Phone OS: <span><?= $phone->getOs() ?></span></h3>
                <h3 class="resolution">Resolution: <span><?= $phone->getResolution() ?></span></h3>
                <h3 class="ram">Ram: <span><?= $phone->getRam() ?></span></h3>
                <h3 class="cpu">Cpu: <span><?= $phone->getCpu() ?></span></h3>
                <h3 class="battery">Battery: <span><?= $phone->getBattery() ?></span></h3>
                <h3 class="description">Description: <span><?= $phone->getDescription() ?></span></h3>
                <h3 class="released">Released: <span><?= $phone->getBattery() ?></span></h3>
                <p><img src='<?= $this->getViewFileUrl('img/' . $phone->getPhoto()); ?>' alt="<?= $phone->getModel() ?>-photo"></p>
                <div class="manufacturer-left">
                    <h3 class="price">Price: <span><?= $phone->getPrice() ?></span></h3>
                    <h3 class="created-at">Created At: <span><?= $phone->getCreatedAt() ?></span></h3>
                    <p>
                        <a class="manufacturer-btn go-back-mobile" href="<?= $block->getUrl('mobile')?>">Go back</a>
                    </p>
                </div>
                <hr>
            </div><br>
        <?php endforeach; ?>
    <?php endif; ?>
</div>